spring:
    application:
        name: linkcutter

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    config:
        import: application-secrets.yaml